name: Sync Specific Files

on:
  push:
    branches:
      - master   # 当 master 分支发生变化时触发
  workflow_dispatch: # 手动触发

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Git 用户
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      # Step 3: 切换到 Tsundere_use 分支（如果不存在则创建）
      - name: Switch to Tsundere_use branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/Tsundere_use; then
            git checkout Tsundere_use
          else
            git checkout --orphan Tsundere_use
            git rm -rf .
            echo "# This branch contains only glm files" > README.md
            git add README.md
            git commit -m "Initialize Tsundere_use branch"
            git push origin Tsundere_use
          fi
      # Step 4: 从 master 分支同步 glm 文件夹下的文件
      - name: Sync glm files
        run: |
          git checkout master -- glm/
          git add glm/
          git commit -m "Sync glm files from master branch" || echo "No changes to commit"
      # Step 5: 推送到 Tsundere_use 分支
      - name: Push changes
        run: |
          git push origin HEAD:Tsundere_use
